### ISSUE TITLE
Safari Big Sur first print attempt - blank page

### ISSUE THREAD

**Issue by dalia-s** [crabbly/Print.js#528]
mackOS Big Sur 11.1
Safari 14.0.2

Reproducible on your own page:
* load https://printjs.crabbly.com
* click on the first available "print" button -> print dialog opens with blank page
* cancel print and click "print" the second time -> "website trying to print dialog" -> print -> all good

![image](https://user-images.githubusercontent.com/22872926/105054837-1aadb100-5a7b-11eb-83fd-bc9d05cc3fbb.png)
![image](https://user-images.githubusercontent.com/22872926/105054951-3ca73380-5a7b-11eb-9241-64a0ff26dbef.png)

**Comment by crabbly** [comment]
I confirmed this issue when printing PDF documents in Safari on Big Sur. My guess is that the browser is flagging the document as cached before its actually finished, therefore the print job seems to be dispatched before the document is available, which results in a blank screen. More browser compatibility "fun" for us to play with :(

**Comment by chsami** [comment]
> I confirmed this issue when printing PDF documents in Safari on Big Sur. My guess is that the browser is flagging the document as cached before its actually finished, therefore the print job seems to be dispatched before the document is available, which results in a blank screen. More browser compatibility "fun" for us to play with :(

Any ETA when this will be fixed?

**Comment by zakariamehbi** [comment]
> I confirmed this issue when printing PDF documents in Safari on Big Sur. My guess is that the browser is flagging the document as cached before its actually finished, therefore the print job seems to be dispatched before the document is available, which results in a blank screen. More browser compatibility "fun" for us to play with :(

I'm having the same issue, I added a timestamp to my document to bypass the cache and my document is already loaded and shown on the page but nothing changes.

**Comment by cliffdeclerck** [comment]
We have the same issue. Has anybody already figured out from which version onwards this problem occurs?

**Comment by hinet2013** [comment]
I'm facing the issue too. In my scenario i'm printing a live generated PDF, whose data is fetched via AJAX.
I've tried to use the library in two different ways, in the hope that a different code path would have workaround-ed the Safari bug, but i had no luck
1) First attempt: generating a local blob and submitting its url to the library
`printJs(blobUrl)`
2) Second attempt: submitting the raw base64 data
```
printJs({
    printable: base64Data,
    base64: true,
    type: 'pdf'
});
```
The bug still occours, while on the other browsers (Edge, FF, Chrome) it works perfectly

**Comment by egonvb** [comment]
I had a hunch the contentWindow in safari wasn't quite ready so I've added a 1 second timeout before calling the print function in performPrint
It seems to fix the problem, curious to know if this is also the case for others.

`function performPrint (iframeElement, params) {
  try {
    iframeElement.focus()
    var 
    // If Edge or IE, try catch with execCommand
    if (Browser.isEdge() || Browser.isIE()) {
      try {
        iframeElement.contentWindow.document.execCommand('print', false, null)
      } catch (e) {
        iframeElement.contentWindow.print()
      }
    } else {
      var contentWindow = e.contentWindow;
                    setTimeout(function() {
                        contentWindow.print();
                        cleanUp(params)
                    }, 2000);
      iframeElement.contentWindow.print()
    }
  } catch (error) {
    params.onError(error)
  } finally {
    if (Browser.isFirefox()) {
      // Move the iframe element off-screen and make it invisible
      iframeElement.style.visibility = 'hidden'
      iframeElement.style.left = '-1px'
      cleanUp(params)
    }
    if( Browser.isEdge() || Browser.isIE() ){
      cleanUp(params)
    }
    
  }
}`

**Comment by jayhoogle** [comment]
I'm facing this issue on Big Sur too. I haven't been able to get it to work first time with any combination of settings so I wondered if anyone had a workaround for the issue without altering the package?

**Comment by mstanowski** [comment]
https://github.com/mstanowski/Print.js/blob/6502c73c7e1ba87346fe4913fa5de6220936095b/src/js/print.js#L16

Changed

`16: if (Browser.isFirefox()) {`

into

`16: if (Browser.isFirefox() || Browser.isSafari()) {`

and works for me now.

**Comment by chsami** [comment]
Do you guys happen to get this popup when printing?

![image](https://user-images.githubusercontent.com/23292806/117940998-f7e52800-b309-11eb-91a6-d3dea5088274.png)

**Comment by odragora** [comment]
Safari 14.1.1 (macOS Big Sur): when I try to print an image, then cancel print prompt and try to open print dialog again, the page to print is blank.

**Comment by Ethaan** [comment]
> Do you guys happen to get this popup when printing on safari?
> 
> ![image](https://user-images.githubusercontent.com/23292806/117940998-f7e52800-b309-11eb-91a6-d3dea5088274.png)
> 
> EDIT: I found out you'll get this popup when you cancel the first print and then try to print again. This popup is also the reason why I always get a blank screen on safari.

Did you get a fix on this issue?

**Comment by into-piece** [comment]
> Do you guys happen to get this popup when printing on safari?
> 
> ![image](https://user-images.githubusercontent.com/23292806/117940998-f7e52800-b309-11eb-91a6-d3dea5088274.png)
> 
> EDIT: I found out you'll get this popup when you cancel the first print and then try to print again. This popup is also the reason why I always get a blank screen on safari.
Same issue here, online waiting, hurry.

**Comment by wmattei** [comment]
Hey @crabbly this seems to have been fixed in this PR: https://github.com/crabbly/Print.js/pull/588
Do you think we can get it merged?

**Comment by SivaramanJ** [comment]
Hi, For me the timeout did not help.  I get the safari's alert message only if i trigger iframe.contentWindow.print(). So even the timeout is helping in this case. 

Is there any way i can disable the pop up ?

**Comment by ftlno** [comment]
any news here yet? Really need printing in safari and firefox..

**Comment by Trimakas** [comment]
Seems to still be an issue.. any word?

**Comment by greardrear** [comment]
Any updates on this issue? I'm using safari 15.1 and still experiencing this, the timeout didn't work for me nor the fact that the entire print function is async and i wait longer then 1 second before the print dialogue opens and displays a blank page, in FF and Chrome it works perfectly

**Comment by kpsharma996** [comment]
Hello all, 
Recently I was getting same issue and I solved it by using below code for safari browser in Angular.

Hope this may help someone.

```
async manualPrint(file: File): Promise<void> {
    this.cleanUp();
    let printable = URL.createObjectURL(file);
    const printFrame = document.createElement('iframe');
    printFrame.setAttribute('style', 'display: none; height: 0; width: 0; position: absolute; border: 0');
    printFrame.id = 'print-frame';
    const resp = await (await fetch(printable)).arrayBuffer();
    let localPDF = new Blob([resp], {type: 'application/pdf'});
    printFrame.src = URL.createObjectURL(localPDF);
    document.body.appendChild(printFrame);
    printFrame.onload = () => {
      setTimeout(() => {
        printFrame.focus();
        printFrame.contentWindow?.print();
      }, 1000);
    }
  }
```

 ```
 cleanUp(): void {
    const iframe = document.getElementById('print-frame')
    if (iframe) {
      iframe.remove()
    }
  }
```

**Comment by mstroming** [comment]
Any update? Thanks.

**Comment by ashutoshsinghjadon** [comment]
I am also experiencing the same issue on safari 14 and 15.1, Any updates on this please? Thanks

**Comment by spacejamjim** [comment]
> https://github.com/mstanowski/Print.js/blob/6502c73c7e1ba87346fe4913fa5de6220936095b/src/js/print.js#L16
> 
> Changed
> 
> `16: if (Browser.isFirefox()) {`
> 
> into
> 
> `16: if (Browser.isFirefox() || Browser.isSafari()) {`
> 
> and works for me now.

I forked this and it works for me as well. I've commented on the PR in hopes of getting a minor release. Though it might be safari, they already implement this logic for Firefox so why not include Safari?

**Comment by daphnesmit** [comment]
The timeout does not help for me

**Comment by daphnesmit** [comment]
Also I send this to Jen Simmons of Safari. curious to see Safari's reaction: https://twitter.com/daphnesmit/status/1491783519386828802

**Comment by daphnesmit** [comment]
Here is a simple repo aswell: https://codepen.io/erikdonohoo/pen/qxeNMe

**Comment by corneliushka** [comment]
Hello, same here. 

At first click, I have the safari print popup with a blank page :
<img width="786" alt="Screenshot 2022-03-04 at 12 04 38" src="https://user-images.githubusercontent.com/39053043/156752149-afe6970f-fdff-417e-9a95-1b092812b35b.png">


After pressing cancel and retrying with a second click, it will invoke the "This web page is trying to print..." popup :

<img width="474" alt="Screenshot 2022-03-04 at 12 05 36" src="https://user-images.githubusercontent.com/39053043/156752316-6b54e74e-16cf-4f42-8237-22d30b389f99.png">

And it works as expected : 
<img width="774" alt="Screenshot 2022-03-04 at 12 09 30" src="https://user-images.githubusercontent.com/39053043/156753282-f32de686-e85c-40f5-985f-29063561f3aa.png">

To reproduce I refresh the window. But it's anoying for the user to cancel the first try everytime. 

Safari : Version 14.0.2 (16610.3.7.1.9) / also tested with Safari 15, same bug. 
print-js : 1.6.0 (I'm aware that a Safari problem)

**Comment by GussieTech** [comment]
@crabbly Not ideal, but how about a hack like this until Safari is fixed.

```js
const print = () => {
  const popup = window.open("", "_blank", "width=1,height=1");
  popup.addEventListener("afterprint", (event) => {
    popup.close();
  });
  const content = document.getElementById("print-target");
  popup.document.head.innerHTML = document.head.innerHTML;
  popup.document.body.innerHTML = content.innerHTML;
  setTimeout(() => {
    popup.print();
    setTimeout(() => {
      popup.close();
    });
  });
};
document.querySelector("button").addEventListener("click", print);
```

https://codepen.io/gussietech/pen/GRQWYVM

**Comment by KRozumniak** [comment]
This issue seems to be resolved for macOS Ventura 13.3.1

**Comment by sc-mickael** [comment]
hi,
problem still relevant today.
Any idea ?
regards
