### ISSUE TITLE
Issue printing PDF using Firefox

### ISSUE THREAD

**Issue by bababash** [crabbly/Print.js#695]
Hello Print.js team,
I'd like to report an I am experiencing using Firefox. This is working perfectly in Chrome

### Implementation:
`<button type="button" onclick="printJS('/static/test.pdf')">Print</button>`
test.pdf was copied from this repository
Using Print.js v1.6.0
Using Firefox v118.0.2 (64-bit)

### Issue:
Upon clicking the button, I get the following output in my console

`Warning: Invalid absolute docBaseUrl: "blob:http://127.0.0.1:8000/ff77f293-d166-45ff-a02a-d3e4c7852f7a".`
>([pdf.worker.js:970:13](resource://pdf.js/build/pdf.worker.js))

`Warning: Bad value, for custom key "AAPL:Keywords", in Info: .`
>([pdf.worker.js:970:13](resource://pdf.js/build/pdf.worker.js))

`PDF 8eed11de459c2ed35fec410bf057a870 [1.3 Mac OS X 10.11.4 Quartz PDFContext / Word] (PDF.js: 3.10.86 [c72cb5436])`
>([viewer.js:1518:13](resource://pdf.js/web/viewer.js))

`Uncaught NS_ERROR_FAILURE:`
>([print.min.js:1:4198])

Hope you can help me!

**Comment by bababash** [comment]
I also tried using [https://www.npmjs.com/package/print-js-updated](https://www.npmjs.com/package/print-js-updated) which resulted in the same error.

Using the version from the CDN [  https://printjs-4de6.kxcdn.com/print.min.js](https://printjs-4de6.kxcdn.com/print.min.js) opens the PDF viewer on Firefox without throwing an error (doesn't print though)

**Comment by SaschaAusUlm** [comment]
Seeing the same:

Warning: Invalid absolute docBaseUrl: "blob:https://xxxxxxxxxxxxxxxxxxxxxxx/126c4566-4c9b-4923-a0a4-ec4aff6591c0". [pdf.worker.js:970:13](resource://pdf.js/build/pdf.worker.js)
PDF 816648aa36057888347bf1df09e19bd1 [1.4 Skia/PDF m79 / Chromium] (PDF.js: 3.10.86 [c72cb5436])

I see the PDF in my UI, but when I print it's just a blank page and the preview is also white. 

It works fine in Edge and Chrome.

Firefox: Version 118.0.2 (64-Bit)

**Comment by SaschaAusUlm** [comment]
I am seeing that there was a fix committed 8 months ago:

[Merge pull request](https://github.com/crabbly/Print.js/commit/1d7eb77ab0953e85bbe584e23f5403b333590e76) https://github.com/crabbly/Print.js/pull/657 [from amoilanen/fix-firefox-110-pdf-printing](https://github.com/crabbly/Print.js/commit/1d7eb77ab0953e85bbe584e23f5403b333590e76)

but no release was done?

**Comment by SaschaAusUlm** [comment]
I tried print-js-updated which includes the made but unreleased fix and with that, it works again for me. Sad that this project is going to waste.

**Comment by bababash** [comment]
Thanks @SaschaAusUlm I'll try again. How did you implement it?

**Comment by SaschaAusUlm** [comment]
Hey @bababash,

for us, printing is just a one-liner:

>   public printReport(): void { printJS({ printable: this.selectedReport.downloadUri, type: 'pdf', showModal: true }); }

with printable being a link to one of our PDFs in one of our Blob storages. To make it work again in Firefox, I just had to pull in the patched library with npm and adjust the import.

**Comment by wmadam** [comment]
Hello, I patched the library with the code from the PR, but I still get a blank page in firefox v119.0 when printing (no errors in console though).
Can anyone reproduce this issue or is there an alternative fix?

**Comment by lucasjuna** [comment]
I've installed `print-js-updated`
Then used `import printJS from "print-js-updated";`
And it's working in latest version of Firefox.
But don`t remove print-js.

**Comment by bababash** [comment]
> Hey @bababash,
> 
> for us, printing is just a one-liner:
> 
> > public printReport(): void { printJS({ printable: this.selectedReport.downloadUri, type: 'pdf', showModal: true }); }
> 
> with printable being a link to one of our PDFs in one of our Blob storages. To make it work again in Firefox, I just had to pull in the patched library with npm and adjust the import.

I tried again with print-js-updated from npm. It appears to have the changes merged in but hard to tell. How come there is a disconnect between npm and github?

The issue still exists with Firefox. Works perfectly in Chrome.
From Firefox console:
```
Source map error: Error: request failed with status 404
Resource URL: "path to printjs"
Source Map URL: print.map

Warning: Invalid absolute docBaseUrl: "blob:http://127.0.0.1:8000/6f9819a6-0357-4486-b648-38dcf047f33c". pdf.worker.mjs:339:13
PDF 8e4fcce84c89827e7d1aa79671646b36 [1.3 pypdf / -] (PDF.js: 4.0.67 [5c45dfa0a]) viewer.mjs:10800:13
Uncaught NS_ERROR_FAILURE: print_updated.js:1:4694
```

**Comment by bababash** [comment]
If anyone else is hunting for a solution, this is what worked for me to print a pdf in chrome/firefox:
[https://gist.github.com/timdown/cfacd32f6b5e439bb02aaf142343ce4c](https://gist.github.com/timdown/cfacd32f6b5e439bb02aaf142343ce4c)

**Comment by mdodge-ecgrow** [comment]
~~I'm also having this same issue.  It seems to work intermittently in Firefox which is baffling.~~

Nevermind, I was able to get it working with print-js-updated.
Thanks!

**Comment by eddielu** [comment]
Looks to be broken now again. Even the example homepage is broken: https://printjs.crabbly.com/. Just shows a blank page.

**Comment by BokuNoMaxi** [comment]
Looks like this repository is dead, for anyone who has the same problem and looking for a fix, there is a fork that works like a charm => https://github.com/ChimneySwift/Print.js/releases/tag/v1.6.1

**Comment by josefjebavy** [comment]
I have same problem.
on version 1.5 and 1.6 .0 -  when i using firefox and use print  it is white page.
Chrome is ok.
version 1.4 or 1.6.1 (https://github.com/ChimneySwift/Print.js/releases/tag/v1.6.1) working

**Comment by dallasbeek** [comment]
Blank page on Firefox as well.

**Comment by passatgt** [comment]
> Blank page on Firefox as well.

Can you try adding this CSS to your site and see if that helps?

```
html body #printJS {
	visibility: visible !important;
}
```

**Comment by richard-muvirimi** [comment]
For anyone looking for a fix using this repo [See this Comment](https://github.com/crabbly/Print.js/pull/682#issuecomment-3165304535)

**Comment by passatgt** [comment]
> For anyone looking for a fix using this repo [See this Comment](https://github.com/crabbly/Print.js/pull/682#issuecomment-3165304535)

Yes, i just checked and that indeed seems to be the correct solution. The npm package has this in the release:

```
if (_browser__WEBPACK_IMPORTED_MODULE_0__["default"].isFirefox()) {
      // Move the iframe element off-screen and make it invisible
      iframeElement.style.visibility = 'hidden';
      iframeElement.style.left = '-1px';
 }
```

So the iframe gets hidden by default in Firefox, causing the blank page issue. However in the source, theres a condition to only do this in older Firefox versions:

https://github.com/crabbly/Print.js/blob/08d002d43a9c383cc26fedbae3c8a6f597666917/src/js/print.js#L75

So either this, or just overwriting the css style like i said above should work. 

Also found this, which seems to include a fresh build: https://www.npmjs.com/package/print-js-updated
Tested and it works(simply use` import printJS from 'print-js-updated'; `for example)

Better yet, theres an even better version mentioned here: https://github.com/crabbly/Print.js/issues/695#issuecomment-2863195751
Which includes the correct Firefox handling and also fixes a similar issue in Safari. To use this, you can install the npm package like so:
`"print-js": "github:ChimneySwift/Print.js",`

And import it like so:
`import printJS from 'print-js/src/index.js';`

**Comment by richard-muvirimi** [comment]
Thanks @passatgt print-js-updated works as expected

**Comment by memen45** [comment]
`printjs-updated` seems to fix printing in firefox, however, on Android in Edge and Chrome, printing does not work. With PrintJS the `onIncompatibleBrowser`  and `onError` could be used to fall back on downloading the content instead. However, this seems to be broken in `print-js-updated`.

Anyone else encountering the same issue?
